server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8    #设置 Tomcat 编码格式
spring:
  datasource:
    # Type 设置使用何种类型的数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql的配置加载驱动类信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    #mysql的连接信息
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #用户名
    username: root
    #密码
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                    # 等待连接获取的最大超时时间
